### PR TITLE
Safari fixes

### PR DESCRIPTION
**Pull request by peggyl**
`Script dashboard error SyntaxError: Unexpected use of reserved word 'let' in strict mode`

Fixed in https://github.com/Clever/grafana-service/commit/062b1b06889dd7cd61f9c9fb45d34a3768f92376.

`Script dashboard error SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.`

Fixed in https://github.com/Clever/grafana-service/commit/a3226e7a7067fa5b9b0d6095a17c51b28b827ac9. Do we want to disable strict mode though? We could also check what the browser agent is, and only skip use-strict for Safari.

### CODE REVIEW

**Comment by peggyl** [comment]
Tested in recent versions of Chrome, Safari, Firefox locally.

**Comment by xavi-** [comment]
lgtm

**Comment by peggyl** [comment]
Hm. I would prefer to keep `use strict` enabled, but I've tried the other following workarounds that were unsuccessful:

- replace `function doSomething(){}` with `var doSomething = function(){}` even though is this not what our style guide recommends. The `Strict mode does not allow function declarations in a lexically nested statement` error message persisted.

- check browser user agent and only use strict mode for non-Safari browsers. It seems `navigator` is undefined when the dashboard is being created, and `navigator.userAgent` is the best method I've found of browser detection so far.

**Comment by peggyl** [comment]
I informally surveyed our eng team on Slack, and roughy ~25/40 people responded: 22 Chrome, 2 Safari, 1 Firefox (people could have chosen > 1).

**Comment by mohit** [comment]
I see a lgtm. Can we push this ❄️

**Comment by peggyl** [comment]
I don't like the idea of removing `use strict` (but perhaps this isn't as bad as it sounds), and can't figure out how to only disable this for Safari. 😢 

Merging for now, will see if this is fixable later (the dashboard will error/crash anyway, so we'll know if something is wrong).

**Pull request merged**
