### PR TITLE
Used Average stat for health host count metric

### PR DESCRIPTION
**Pull request by xavi-**
Old style:
image

With average:
image

### CODE REVIEW

**Comment by mohit** [comment]
Lgtm

**Comment by rgarcia** [comment]
I don't understand... what does it even mean to take the average or min of healthy hosts?

**Comment by xavi-** [comment]
I don't really understand either.  We ran into a couple of couple AWS signal with seemingly unrelated values for min, max, average.  One possibility is that the ALB metric has a data point for each backend: a 1 if the backend is healthy and a 0 if it's not.  So if one backend is unhealthy the min of the 60 points is 0.

**Comment by rgarcia** [comment]
Do you mind filing a support ticket with them? This seems like a metric we
should understand well

**Pull request merged**
