### PR TITLE
Fix metric name for ELB 5xx status codes

### PR DESCRIPTION
**Pull request by peggyl**

### CODE REVIEW

**Comment by dfuentes** [comment]
This doesn't really fix the issue.  The query for 4xx is still returning null, which breaks the graph.  Still looking into a fix

**Comment by dfuentes** [comment]
FYI, I've fixed these graphs by splitting 5xx and 4xx, along with some other minor tweaks here https://github.com/Clever/grafana-service/pull/43

**Comment by Christopher-Bradshaw** [comment]
If it is hard getting both 4xx and 5xx on that graph, I can't actually think of many cases where we would care about anything other than the 5xx's.

**Comment by peggyl** [comment]
Feel free to close this PR – I just took a quick look since I created that panel and had some context, and this stuck out as a reason why 5xx metrics might be missing entirely…

**Pull request closed without merging**
